var products = [
  {
    id: 1,
    name: "Beyond Burger",
    description: "Plant-based Patties.",
    brand: "Beyond Meat",
    category: ["hamburger",
      "vegan"],
    weigth: 226,
    price: 10.90,
    available: true,
    discount: 0
  },
  {
    id: 2,
    name: "Beyond Beef",
    description: "Plant-based Beef.",
    brand: "Beyond Meat",
    category: ["beef",
      "vegan"],
    weigth: 453,
    price: 15.90,
    available: true,
    discount: 0
  },
  {
    id: 3,
    name: "Lightlife Burger",
    description: "Plant-based Sausage.",
    brand: "Lightlife",
    category: ["hamburger"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  },
  {
    id: 4,
    name: "Beyond Sausage",
    description: "Plant-based Sausage.",
    brand: "Beyond Meat",
    category: ["sausage",
      "vegan"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  },
  {
    id: 1,
    name: "Beyond Burger",
    description: "Plant-based Patties.",
    brand: "Beyond Meat",
    category: ["hamburger",
      "vegan"],
    weigth: 226,
    price: 10.90,
    available: true,
    discount: 0
  },
  {
    id: 2,
    name: "Beyond Beef",
    description: "Plant-based Beef.",
    brand: "Beyond Meat",
    category: ["beef",
      "vegan"],
    weigth: 453,
    price: 15.90,
    available: true,
    discount: 0
  },
  {
    id: 3,
    name: "Lightlife Burger",
    description: "Plant-based Sausage.",
    brand: "Lightlife",
    category: ["hamburger"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  },
  {
    id: 4,
    name: "Beyond Sausage",
    description: "Plant-based Sausage.",
    brand: "Beyond Meat",
    category: ["sausage",
      "vegan"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  },  {
    id: 1,
    name: "Beyond Burger",
    description: "Plant-based Patties.",
    brand: "Beyond Meat",
    category: ["hamburger",
      "vegan"],
    weigth: 226,
    price: 10.90,
    available: true,
    discount: 0
  },
  {
    id: 2,
    name: "Beyond Beef",
    description: "Plant-based Beef.",
    brand: "Beyond Meat",
    category: ["beef",
      "vegan"],
    weigth: 453,
    price: 15.90,
    available: true,
    discount: 0
  },
  {
    id: 3,
    name: "Lightlife Burger",
    description: "Plant-based Sausage.",
    brand: "Lightlife",
    category: ["hamburger"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  },
  {
    id: 4,
    name: "Beyond Sausage",
    description: "Plant-based Sausage.",
    brand: "Beyond Meat",
    category: ["sausage",
      "vegan"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  },
  {
    id: 2,
    name: "Beyond BURGOYSE",
    description: "Plant-based Patties.",
    brand: "Beyond Meat",
    category: ["hamburger",
      "vegan"],
    weigth: 226,
    price: 10.90,
    available: true,
    discount: 0
  },
  {
    id: 3,
    name: "Beyond Beef",
    description: "Plant-based Beef.",
    brand: "Beyond Meat",
    category: ["beef",
      "vegan"],
    weigth: 453,
    price: 15.90,
    available: true,
    discount: 0
  },
  {
    id: 3,
    name: "Lightlife Burger",
    description: "Plant-based Sausage.",
    brand: "Lightlife",
    category: ["hamburger"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  },
  {
    id: 4,
    name: "Beyond SAUSAUGE",
    description: "Plant-based Sausage.",
    brand: "Beyond Meat",
    category: ["sausage",
      "vegan"],
    weigth: 400,
    price: 11.50,
    available: true,
    discount: 0
  }
];
